// Central registry of all NetBox-like resource modules and their schema
// Defines navigation, fields, and form behavior. Drives the entire frontend.

export const NAV_GROUPS = [
  {
    label: 'Organization',
    icon: 'building-2',
    items: [
      { path: 'sites', label: 'Sites' },
      { path: 'site-groups', label: 'Site Groups' },
      { path: 'regions', label: 'Regions' },
      { path: 'locations', label: 'Locations' },
      { path: 'tenants', label: 'Tenants' },
      { path: 'tenant-groups', label: 'Tenant Groups' },
      { path: 'contacts', label: 'Contacts' },
      { path: 'contact-groups', label: 'Contact Groups' },
      { path: 'contact-roles', label: 'Contact Roles' },
      { path: 'contact-assignments', label: 'Contact Assignments' },
    ],
  },
  {
    label: 'Devices',
    icon: 'server',
    items: [
      { path: 'devices', label: 'Devices' },
      { path: 'device-types', label: 'Device Types' },
      { path: 'device-roles', label: 'Device Roles' },
      { path: 'platforms', label: 'Platforms' },
      { path: 'manufacturers', label: 'Manufacturers' },
      { path: 'modules', label: 'Modules' },
      { path: 'module-types', label: 'Module Types' },
      { path: 'virtual-chassis', label: 'Virtual Chassis' },
      { path: 'virtual-device-contexts', label: 'Virtual Device Contexts' },
      { path: 'inventory-items', label: 'Inventory Items' },
      { path: 'inventory-item-roles', label: 'Inventory Item Roles' },
    ],
  },
  {
    label: 'Racks',
    icon: 'columns-3',
    items: [
      { path: 'racks', label: 'Racks' },
      { path: 'rack-roles', label: 'Rack Roles' },
      { path: 'rack-reservations', label: 'Rack Reservations' },
      { path: 'rack-elevation', label: 'Rack Elevation View', special: true },
    ],
  },
  {
    label: 'Connections',
    icon: 'cable',
    items: [
      { path: 'cables', label: 'Cables' },
      { path: 'interfaces', label: 'Interfaces' },
      { path: 'console-ports', label: 'Console Ports' },
      { path: 'console-server-ports', label: 'Console Server Ports' },
      { path: 'power-ports', label: 'Power Ports' },
      { path: 'power-outlets', label: 'Power Outlets' },
      { path: 'front-ports', label: 'Front Ports' },
      { path: 'rear-ports', label: 'Rear Ports' },
      { path: 'module-bays', label: 'Module Bays' },
      { path: 'device-bays', label: 'Device Bays' },
      { path: 'cable-trace', label: 'Cable Trace', special: true },
    ],
  },
  {
    label: 'IPAM',
    icon: 'globe',
    items: [
      { path: 'ip-addresses', label: 'IP Addresses' },
      { path: 'ip-ranges', label: 'IP Ranges' },
      { path: 'prefixes', label: 'Prefixes' },
      { path: 'aggregates', label: 'Aggregates' },
      { path: 'prefix-tree', label: 'Prefix Tree', special: true },
      { path: 'vlans', label: 'VLANs' },
      { path: 'vlan-groups', label: 'VLAN Groups' },
      { path: 'vrfs', label: 'VRFs' },
      { path: 'route-targets', label: 'Route Targets' },
      { path: 'rirs', label: 'RIRs' },
      { path: 'asns', label: 'ASNs' },
      { path: 'asn-ranges', label: 'ASN Ranges' },
      { path: 'roles', label: 'Roles' },
      { path: 'services', label: 'Services' },
      { path: 'service-templates', label: 'Service Templates' },
      { path: 'fhrp-groups', label: 'FHRP Groups' },
      { path: 'fhrp-group-assignments', label: 'FHRP Assignments' },
    ],
  },
  {
    label: 'Circuits',
    icon: 'route',
    items: [
      { path: 'circuits', label: 'Circuits' },
      { path: 'circuit-types', label: 'Circuit Types' },
      { path: 'circuit-terminations', label: 'Circuit Terminations' },
      { path: 'providers', label: 'Providers' },
      { path: 'provider-accounts', label: 'Provider Accounts' },
      { path: 'provider-networks', label: 'Provider Networks' },
    ],
  },
  {
    label: 'Power',
    icon: 'zap',
    items: [
      { path: 'power-panels', label: 'Power Panels' },
      { path: 'power-feeds', label: 'Power Feeds' },
    ],
  },
  {
    label: 'Virtualization',
    icon: 'box',
    items: [
      { path: 'virtual-machines', label: 'Virtual Machines' },
      { path: 'clusters', label: 'Clusters' },
      { path: 'cluster-types', label: 'Cluster Types' },
      { path: 'cluster-groups', label: 'Cluster Groups' },
      { path: 'vm-interfaces', label: 'VM Interfaces' },
      { path: 'virtual-disks', label: 'Virtual Disks' },
    ],
  },
  {
    label: 'Wireless',
    icon: 'wifi',
    items: [
      { path: 'wireless-lans', label: 'Wireless LANs' },
      { path: 'wireless-lan-groups', label: 'Wireless LAN Groups' },
      { path: 'wireless-links', label: 'Wireless Links' },
    ],
  },
  {
    label: 'VPN',
    icon: 'shield',
    items: [
      { path: 'tunnels', label: 'Tunnels' },
      { path: 'tunnel-groups', label: 'Tunnel Groups' },
      { path: 'tunnel-terminations', label: 'Tunnel Terminations' },
      { path: 'l2vpns', label: 'L2VPNs' },
      { path: 'l2vpn-terminations', label: 'L2VPN Terminations' },
      { path: 'ike-proposals', label: 'IKE Proposals' },
      { path: 'ike-policies', label: 'IKE Policies' },
      { path: 'ipsec-proposals', label: 'IPSec Proposals' },
      { path: 'ipsec-policies', label: 'IPSec Policies' },
      { path: 'ipsec-profiles', label: 'IPSec Profiles' },
    ],
  },
  {
    label: 'Discovery',
    icon: 'radar',
    items: [
      { path: 'discovery', label: 'Dashboard', special: true },
      { path: 'discovery/credentials', label: 'Credentials', special: true },
      { path: 'discovery/jobs', label: 'Discovery Jobs', special: true },
      { path: 'discovery/devices', label: 'Discovered Devices', special: true },
      { path: 'discovery/topology', label: 'Network Topology', special: true },
      { path: 'discovery/netdisco', label: 'Netdisco Sync', special: true },
    ],
  },
  {
    label: 'Customization',
    icon: 'settings-2',
    items: [
      { path: 'tags', label: 'Tags' },
      { path: 'custom-fields', label: 'Custom Fields' },
      { path: 'custom-links', label: 'Custom Links' },
      { path: 'config-contexts', label: 'Config Contexts' },
      { path: 'config-templates', label: 'Config Templates' },
      { path: 'webhooks', label: 'Webhooks' },
      { path: 'saved-filters', label: 'Saved Filters' },
      { path: 'journal-entries', label: 'Journal Entries' },
      { path: 'image-attachments', label: 'Image Attachments' },
      { path: 'changelog', label: 'Change Log', special: true },
    ],
  },
  {
    label: 'Admin',
    icon: 'shield-check',
    items: [
      { path: 'admin/users', label: 'Users', special: true },
      { path: 'admin/groups', label: 'Groups', special: true },
      { path: 'admin/api-tokens', label: 'API Tokens', special: true },
      { path: 'graphql', label: 'GraphQL Playground', special: true },
    ],
  },
];

// Field schemas per resource. Each field: { name, label, type, required?, options?, fk? }
// type: text, textarea, number, boolean, select, multiselect, json, tags, color, fk
// fk: { resource, displayField }
const common = [
  { name: 'description', label: 'Description', type: 'text' },
  { name: 'comments', label: 'Comments', type: 'textarea' },
  { name: 'tags', label: 'Tags', type: 'tags' },
];

const withName = (extra = []) => [{ name: 'name', label: 'Name', type: 'text', required: true }, ...extra, ...common];
const slug = { name: 'slug', label: 'Slug', type: 'text' };

const STATUS_OPTIONS = ['planned', 'staging', 'active', 'decommissioning', 'retired', 'offline'];

export const RESOURCES = {
  // Organization
  'regions': { label: 'Region', titleField: 'name', fields: withName([slug, { name: 'parent_id', label: 'Parent Region', type: 'fk', fk: { resource: 'regions', displayField: 'name' } }]) },
  'site-groups': { label: 'Site Group', titleField: 'name', fields: withName([slug, { name: 'parent_id', label: 'Parent', type: 'fk', fk: { resource: 'site-groups', displayField: 'name' } }]) },
  'sites': { label: 'Site', titleField: 'name', fields: withName([
    slug,
    { name: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
    { name: 'region_id', label: 'Region', type: 'fk', fk: { resource: 'regions', displayField: 'name' } },
    { name: 'group_id', label: 'Site Group', type: 'fk', fk: { resource: 'site-groups', displayField: 'name' } },
    { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } },
    { name: 'facility', label: 'Facility', type: 'text' },
    { name: 'time_zone', label: 'Time Zone', type: 'text' },
    { name: 'physical_address', label: 'Physical Address', type: 'textarea' },
    { name: 'shipping_address', label: 'Shipping Address', type: 'textarea' },
    { name: 'latitude', label: 'Latitude', type: 'number' },
    { name: 'longitude', label: 'Longitude', type: 'number' },
  ]) },
  'locations': { label: 'Location', titleField: 'name', fields: withName([
    slug,
    { name: 'site_id', label: 'Site', type: 'fk', required: true, fk: { resource: 'sites', displayField: 'name' } },
    { name: 'parent_id', label: 'Parent', type: 'fk', fk: { resource: 'locations', displayField: 'name' } },
    { name: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
    { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } },
    { name: 'facility', label: 'Facility', type: 'text' },
  ]) },
  'tenant-groups': { label: 'Tenant Group', titleField: 'name', fields: withName([slug, { name: 'parent_id', label: 'Parent', type: 'fk', fk: { resource: 'tenant-groups', displayField: 'name' } }]) },
  'tenants': { label: 'Tenant', titleField: 'name', fields: withName([slug, { name: 'group_id', label: 'Group', type: 'fk', fk: { resource: 'tenant-groups', displayField: 'name' } }]) },
  'contact-groups': { label: 'Contact Group', titleField: 'name', fields: withName([slug, { name: 'parent_id', label: 'Parent', type: 'fk', fk: { resource: 'contact-groups', displayField: 'name' } }]) },
  'contact-roles': { label: 'Contact Role', titleField: 'name', fields: withName([slug]) },
  'contacts': { label: 'Contact', titleField: 'name', fields: withName([
    { name: 'group_id', label: 'Group', type: 'fk', fk: { resource: 'contact-groups', displayField: 'name' } },
    { name: 'title', label: 'Title', type: 'text' },
    { name: 'phone', label: 'Phone', type: 'text' },
    { name: 'email', label: 'Email', type: 'text' },
    { name: 'address', label: 'Address', type: 'textarea' },
    { name: 'link', label: 'Link', type: 'text' },
  ]) },
  'contact-assignments': { label: 'Contact Assignment', titleField: 'object_id', fields: [
    { name: 'content_type', label: 'Content Type', type: 'text', required: true },
    { name: 'object_id', label: 'Object ID', type: 'text', required: true },
    { name: 'contact_id', label: 'Contact', type: 'fk', required: true, fk: { resource: 'contacts', displayField: 'name' } },
    { name: 'role_id', label: 'Role', type: 'fk', fk: { resource: 'contact-roles', displayField: 'name' } },
    { name: 'priority', label: 'Priority', type: 'select', options: ['primary', 'secondary', 'tertiary', 'inactive'] },
    ...common,
  ] },
  // Racks
  'rack-roles': { label: 'Rack Role', titleField: 'name', fields: withName([slug, { name: 'color', label: 'Color', type: 'color' }]) },
  'racks': { label: 'Rack', titleField: 'name', fields: withName([
    { name: 'facility_id', label: 'Facility ID', type: 'text' },
    { name: 'site_id', label: 'Site', type: 'fk', required: true, fk: { resource: 'sites', displayField: 'name' } },
    { name: 'location_id', label: 'Location', type: 'fk', fk: { resource: 'locations', displayField: 'name' } },
    { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } },
    { name: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
    { name: 'role_id', label: 'Role', type: 'fk', fk: { resource: 'rack-roles', displayField: 'name' } },
    { name: 'type', label: 'Type', type: 'select', options: ['2-post-frame', '4-post-frame', '4-post-cabinet', 'wall-frame', 'wall-cabinet'] },
    { name: 'width', label: 'Width (inches)', type: 'select', options: ['10', '19', '21', '23'] },
    { name: 'u_height', label: 'U Height', type: 'number' },
    { name: 'starting_unit', label: 'Starting Unit', type: 'number' },
    { name: 'desc_units', label: 'Descending Units', type: 'boolean' },
    { name: 'serial', label: 'Serial', type: 'text' },
    { name: 'asset_tag', label: 'Asset Tag', type: 'text' },
    { name: 'outer_width', label: 'Outer Width', type: 'number' },
    { name: 'outer_depth', label: 'Outer Depth', type: 'number' },
    { name: 'weight', label: 'Weight', type: 'number' },
    { name: 'max_weight', label: 'Max Weight', type: 'number' },
    { name: 'mounting_depth', label: 'Mounting Depth', type: 'number' },
  ]) },
  'rack-reservations': { label: 'Rack Reservation', titleField: 'rack_id', fields: [
    { name: 'rack_id', label: 'Rack', type: 'fk', required: true, fk: { resource: 'racks', displayField: 'name' } },
    { name: 'units', label: 'Units (comma-separated)', type: 'json' },
    { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } },
    ...common,
  ] },
  // Devices
  'manufacturers': { label: 'Manufacturer', titleField: 'name', fields: withName([slug]) },
  'device-types': { label: 'Device Type', titleField: 'model', fields: [
    { name: 'manufacturer_id', label: 'Manufacturer', type: 'fk', required: true, fk: { resource: 'manufacturers', displayField: 'name' } },
    { name: 'model', label: 'Model', type: 'text', required: true },
    slug,
    { name: 'part_number', label: 'Part Number', type: 'text' },
    { name: 'u_height', label: 'U Height', type: 'number' },
    { name: 'is_full_depth', label: 'Full Depth', type: 'boolean' },
    { name: 'subdevice_role', label: 'Subdevice Role', type: 'select', options: ['', 'parent', 'child'] },
    { name: 'airflow', label: 'Airflow', type: 'select', options: ['', 'front-to-rear', 'rear-to-front', 'left-to-right', 'right-to-left', 'side-to-rear', 'passive'] },
    { name: 'weight', label: 'Weight', type: 'number' },
    ...common,
  ] },
  'module-types': { label: 'Module Type', titleField: 'model', fields: [
    { name: 'manufacturer_id', label: 'Manufacturer', type: 'fk', required: true, fk: { resource: 'manufacturers', displayField: 'name' } },
    { name: 'model', label: 'Model', type: 'text', required: true },
    { name: 'part_number', label: 'Part Number', type: 'text' },
    { name: 'weight', label: 'Weight', type: 'number' },
    ...common,
  ] },
  'device-roles': { label: 'Device Role', titleField: 'name', fields: withName([slug, { name: 'color', label: 'Color', type: 'color' }, { name: 'vm_role', label: 'VM Role', type: 'boolean' }]) },
  'platforms': { label: 'Platform', titleField: 'name', fields: withName([slug, { name: 'manufacturer_id', label: 'Manufacturer', type: 'fk', fk: { resource: 'manufacturers', displayField: 'name' } }, { name: 'napalm_driver', label: 'NAPALM Driver', type: 'text' }]) },
  'devices': { label: 'Device', titleField: 'name', fields: [
    { name: 'name', label: 'Name', type: 'text' },
    { name: 'device_type_id', label: 'Device Type', type: 'fk', required: true, fk: { resource: 'device-types', displayField: 'model' } },
    { name: 'role_id', label: 'Role', type: 'fk', required: true, fk: { resource: 'device-roles', displayField: 'name' } },
    { name: 'platform_id', label: 'Platform', type: 'fk', fk: { resource: 'platforms', displayField: 'name' } },
    { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } },
    { name: 'site_id', label: 'Site', type: 'fk', required: true, fk: { resource: 'sites', displayField: 'name' } },
    { name: 'location_id', label: 'Location', type: 'fk', fk: { resource: 'locations', displayField: 'name' } },
    { name: 'rack_id', label: 'Rack', type: 'fk', fk: { resource: 'racks', displayField: 'name' } },
    { name: 'position', label: 'Rack U Position', type: 'number' },
    { name: 'face', label: 'Rack Face', type: 'select', options: ['', 'front', 'rear'] },
    { name: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
    { name: 'serial', label: 'Serial', type: 'text' },
    { name: 'asset_tag', label: 'Asset Tag', type: 'text' },
    { name: 'cluster_id', label: 'Cluster', type: 'fk', fk: { resource: 'clusters', displayField: 'name' } },
    { name: 'virtual_chassis_id', label: 'Virtual Chassis', type: 'fk', fk: { resource: 'virtual-chassis', displayField: 'name' } },
    { name: 'vc_position', label: 'VC Position', type: 'number' },
    { name: 'vc_priority', label: 'VC Priority', type: 'number' },
    { name: 'airflow', label: 'Airflow', type: 'select', options: ['', 'front-to-rear', 'rear-to-front', 'left-to-right', 'right-to-left', 'side-to-rear', 'passive'] },
    { name: 'latitude', label: 'Latitude', type: 'number' },
    { name: 'longitude', label: 'Longitude', type: 'number' },
    ...common,
  ] },
  'modules': { label: 'Module', titleField: 'serial', fields: [
    { name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } },
    { name: 'module_bay_id', label: 'Module Bay', type: 'fk', fk: { resource: 'module-bays', displayField: 'name' } },
    { name: 'module_type_id', label: 'Module Type', type: 'fk', required: true, fk: { resource: 'module-types', displayField: 'model' } },
    { name: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
    { name: 'serial', label: 'Serial', type: 'text' },
    { name: 'asset_tag', label: 'Asset Tag', type: 'text' },
    ...common,
  ] },
  'virtual-chassis': { label: 'Virtual Chassis', titleField: 'name', fields: withName([{ name: 'domain', label: 'Domain', type: 'text' }, { name: 'master_id', label: 'Master Device', type: 'fk', fk: { resource: 'devices', displayField: 'name' } }]) },
  'virtual-device-contexts': { label: 'VDC', titleField: 'name', fields: withName([
    { name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } },
    { name: 'identifier', label: 'Identifier', type: 'text' },
    { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } },
    { name: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
  ]) },
  'inventory-item-roles': { label: 'Inventory Item Role', titleField: 'name', fields: withName([slug, { name: 'color', label: 'Color', type: 'color' }]) },
  'inventory-items': { label: 'Inventory Item', titleField: 'name', fields: [
    { name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } },
    { name: 'parent_id', label: 'Parent', type: 'fk', fk: { resource: 'inventory-items', displayField: 'name' } },
    { name: 'name', label: 'Name', type: 'text', required: true },
    { name: 'label', label: 'Label', type: 'text' },
    { name: 'role_id', label: 'Role', type: 'fk', fk: { resource: 'inventory-item-roles', displayField: 'name' } },
    { name: 'manufacturer_id', label: 'Manufacturer', type: 'fk', fk: { resource: 'manufacturers', displayField: 'name' } },
    { name: 'part_id', label: 'Part ID', type: 'text' },
    { name: 'serial', label: 'Serial', type: 'text' },
    { name: 'asset_tag', label: 'Asset Tag', type: 'text' },
    { name: 'discovered', label: 'Discovered', type: 'boolean' },
    ...common,
  ] },
  // Connections - basic component schemas
  'interfaces': { label: 'Interface', titleField: 'name', fields: [
    { name: 'device_id', label: 'Device', type: 'fk', fk: { resource: 'devices', displayField: 'name' } },
    { name: 'virtual_machine_id', label: 'VM', type: 'fk', fk: { resource: 'virtual-machines', displayField: 'name' } },
    { name: 'name', label: 'Name', type: 'text', required: true },
    { name: 'label', label: 'Label', type: 'text' },
    { name: 'type', label: 'Type', type: 'select', options: ['virtual', 'lag', '1000base-t', '2.5gbase-t', '5gbase-t', '10gbase-t', '10gbase-x-sfpp', '25gbase-x-sfp28', '40gbase-x-qsfpp', '50gbase-x-sfp56', '100gbase-x-qsfp28', '200gbase-x-qsfp56', '400gbase-x-qsfpdd', 'ieee802.11a', 'ieee802.11g', 'ieee802.11n', 'ieee802.11ac', 'ieee802.11ax', 'other'] },
    { name: 'enabled', label: 'Enabled', type: 'boolean' },
    { name: 'mtu', label: 'MTU', type: 'number' },
    { name: 'mac_address', label: 'MAC Address', type: 'text' },
    { name: 'speed', label: 'Speed (kbps)', type: 'number' },
    { name: 'duplex', label: 'Duplex', type: 'select', options: ['', 'half', 'full', 'auto'] },
    { name: 'mgmt_only', label: 'Management Only', type: 'boolean' },
    { name: 'mode', label: 'Mode', type: 'select', options: ['', 'access', 'tagged', 'tagged-all'] },
    { name: 'vrf_id', label: 'VRF', type: 'fk', fk: { resource: 'vrfs', displayField: 'name' } },
    ...common,
  ] },
  'console-ports': { label: 'Console Port', titleField: 'name', fields: [{ name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Type', type: 'select', options: ['', 'de-9', 'db-25', 'rj-11', 'rj-12', 'rj-45', 'mini-din-8', 'usb-a', 'usb-b', 'usb-c', 'usb-mini-a', 'usb-mini-b', 'usb-micro-a', 'usb-micro-b', 'other'] }, ...common] },
  'console-server-ports': { label: 'Console Server Port', titleField: 'name', fields: [{ name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Type', type: 'select', options: ['', 'de-9', 'db-25', 'rj-45', 'usb-a', 'usb-b', 'other'] }, ...common] },
  'power-ports': { label: 'Power Port', titleField: 'name', fields: [{ name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Type', type: 'select', options: ['', 'iec-60320-c6', 'iec-60320-c8', 'iec-60320-c14', 'iec-60320-c16', 'iec-60320-c20', 'iec-60309-p-n-e-4h', 'nema-1-15p', 'nema-5-15p', 'nema-5-20p', 'other'] }, { name: 'maximum_draw', label: 'Maximum Draw (W)', type: 'number' }, { name: 'allocated_draw', label: 'Allocated Draw (W)', type: 'number' }, ...common] },
  'power-outlets': { label: 'Power Outlet', titleField: 'name', fields: [{ name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Type', type: 'text' }, { name: 'power_port_id', label: 'Power Port', type: 'fk', fk: { resource: 'power-ports', displayField: 'name' } }, { name: 'feed_leg', label: 'Feed Leg', type: 'select', options: ['', 'A', 'B', 'C'] }, ...common] },
  'front-ports': { label: 'Front Port', titleField: 'name', fields: [{ name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Type', type: 'text' }, { name: 'rear_port_id', label: 'Rear Port', type: 'fk', fk: { resource: 'rear-ports', displayField: 'name' } }, { name: 'rear_port_position', label: 'Rear Port Position', type: 'number' }, { name: 'color', label: 'Color', type: 'color' }, ...common] },
  'rear-ports': { label: 'Rear Port', titleField: 'name', fields: [{ name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'type', label: 'Type', type: 'text' }, { name: 'positions', label: 'Positions', type: 'number' }, { name: 'color', label: 'Color', type: 'color' }, ...common] },
  'module-bays': { label: 'Module Bay', titleField: 'name', fields: [{ name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'label', label: 'Label', type: 'text' }, { name: 'position', label: 'Position', type: 'text' }, ...common] },
  'device-bays': { label: 'Device Bay', titleField: 'name', fields: [{ name: 'device_id', label: 'Device', type: 'fk', required: true, fk: { resource: 'devices', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'label', label: 'Label', type: 'text' }, { name: 'installed_device_id', label: 'Installed Device', type: 'fk', fk: { resource: 'devices', displayField: 'name' } }, ...common] },
  'cables': { label: 'Cable', titleField: 'label', fields: [
    { name: 'a_terminations', label: 'A Terminations (JSON [{object_type, object_id}])', type: 'json', required: true },
    { name: 'b_terminations', label: 'B Terminations (JSON [{object_type, object_id}])', type: 'json', required: true },
    { name: 'type', label: 'Type', type: 'select', options: ['', 'cat3', 'cat5', 'cat5e', 'cat6', 'cat6a', 'cat7', 'cat7a', 'cat8', 'dac-active', 'dac-passive', 'mrj21-trunk', 'coaxial', 'mmf', 'mmf-om1', 'mmf-om2', 'mmf-om3', 'mmf-om4', 'mmf-om5', 'smf', 'smf-os1', 'smf-os2', 'aoc', 'power', 'usb'] },
    { name: 'status', label: 'Status', type: 'select', options: ['connected', 'planned', 'decommissioning'] },
    { name: 'label', label: 'Label', type: 'text' },
    { name: 'color', label: 'Color', type: 'color' },
    { name: 'length', label: 'Length', type: 'number' },
    { name: 'length_unit', label: 'Length Unit', type: 'select', options: ['m', 'cm', 'ft', 'in', 'km', 'mi'] },
    { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } },
    ...common,
  ] },
  // IPAM
  'rirs': { label: 'RIR', titleField: 'name', fields: withName([slug, { name: 'is_private', label: 'Is Private', type: 'boolean' }]) },
  'asn-ranges': { label: 'ASN Range', titleField: 'name', fields: withName([slug, { name: 'rir_id', label: 'RIR', type: 'fk', required: true, fk: { resource: 'rirs', displayField: 'name' } }, { name: 'start', label: 'Start', type: 'number', required: true }, { name: 'end', label: 'End', type: 'number', required: true }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }]) },
  'asns': { label: 'ASN', titleField: 'asn', fields: [{ name: 'asn', label: 'ASN', type: 'number', required: true }, { name: 'rir_id', label: 'RIR', type: 'fk', required: true, fk: { resource: 'rirs', displayField: 'name' } }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, ...common] },
  'aggregates': { label: 'Aggregate', titleField: 'prefix', fields: [{ name: 'prefix', label: 'Prefix (CIDR)', type: 'text', required: true }, { name: 'rir_id', label: 'RIR', type: 'fk', required: true, fk: { resource: 'rirs', displayField: 'name' } }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, { name: 'date_added', label: 'Date Added', type: 'text' }, ...common] },
  'roles': { label: 'Role', titleField: 'name', fields: withName([slug, { name: 'weight', label: 'Weight', type: 'number' }]) },
  'prefixes': { label: 'Prefix', titleField: 'prefix', fields: [
    { name: 'prefix', label: 'Prefix (CIDR)', type: 'text', required: true },
    { name: 'site_id', label: 'Site', type: 'fk', fk: { resource: 'sites', displayField: 'name' } },
    { name: 'vrf_id', label: 'VRF', type: 'fk', fk: { resource: 'vrfs', displayField: 'name' } },
    { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } },
    { name: 'vlan_id', label: 'VLAN', type: 'fk', fk: { resource: 'vlans', displayField: 'name' } },
    { name: 'status', label: 'Status', type: 'select', options: ['container', 'active', 'reserved', 'deprecated'] },
    { name: 'role_id', label: 'Role', type: 'fk', fk: { resource: 'roles', displayField: 'name' } },
    { name: 'is_pool', label: 'Is Pool', type: 'boolean' },
    { name: 'mark_utilized', label: 'Mark Utilized', type: 'boolean' },
    ...common,
  ] },
  'ip-ranges': { label: 'IP Range', titleField: 'start_address', fields: [{ name: 'start_address', label: 'Start', type: 'text', required: true }, { name: 'end_address', label: 'End', type: 'text', required: true }, { name: 'vrf_id', label: 'VRF', type: 'fk', fk: { resource: 'vrfs', displayField: 'name' } }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, { name: 'status', label: 'Status', type: 'select', options: ['active', 'reserved', 'deprecated'] }, { name: 'role_id', label: 'Role', type: 'fk', fk: { resource: 'roles', displayField: 'name' } }, ...common] },
  'ip-addresses': { label: 'IP Address', titleField: 'address', fields: [
    { name: 'address', label: 'Address (CIDR)', type: 'text', required: true },
    { name: 'vrf_id', label: 'VRF', type: 'fk', fk: { resource: 'vrfs', displayField: 'name' } },
    { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } },
    { name: 'status', label: 'Status', type: 'select', options: ['active', 'reserved', 'deprecated', 'dhcp', 'slaac'] },
    { name: 'role', label: 'Role', type: 'select', options: ['', 'loopback', 'secondary', 'anycast', 'vip', 'vrrp', 'hsrp', 'glbp', 'carp'] },
    { name: 'assigned_object_type', label: 'Assigned Object Type', type: 'select', options: ['', 'interface', 'vminterface', 'fhrpgroup'] },
    { name: 'assigned_object_id', label: 'Assigned Object ID', type: 'text' },
    { name: 'nat_inside_id', label: 'NAT Inside IP', type: 'fk', fk: { resource: 'ip-addresses', displayField: 'address' } },
    { name: 'dns_name', label: 'DNS Name', type: 'text' },
    ...common,
  ] },
  'vrfs': { label: 'VRF', titleField: 'name', fields: withName([{ name: 'rd', label: 'Route Distinguisher', type: 'text' }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, { name: 'enforce_unique', label: 'Enforce Unique IPs', type: 'boolean' }]) },
  'route-targets': { label: 'Route Target', titleField: 'name', fields: withName([{ name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }]) },
  'vlan-groups': { label: 'VLAN Group', titleField: 'name', fields: withName([slug, { name: 'min_vid', label: 'Min VID', type: 'number' }, { name: 'max_vid', label: 'Max VID', type: 'number' }]) },
  'vlans': { label: 'VLAN', titleField: 'name', fields: [{ name: 'vid', label: 'VID', type: 'number', required: true }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'site_id', label: 'Site', type: 'fk', fk: { resource: 'sites', displayField: 'name' } }, { name: 'group_id', label: 'Group', type: 'fk', fk: { resource: 'vlan-groups', displayField: 'name' } }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, { name: 'status', label: 'Status', type: 'select', options: ['active', 'reserved', 'deprecated'] }, { name: 'role_id', label: 'Role', type: 'fk', fk: { resource: 'roles', displayField: 'name' } }, ...common] },
  'service-templates': { label: 'Service Template', titleField: 'name', fields: withName([{ name: 'protocol', label: 'Protocol', type: 'select', options: ['tcp', 'udp', 'sctp'] }, { name: 'ports', label: 'Ports (JSON [1,2,3])', type: 'json' }]) },
  'services': { label: 'Service', titleField: 'name', fields: withName([{ name: 'protocol', label: 'Protocol', type: 'select', options: ['tcp', 'udp', 'sctp'] }, { name: 'ports', label: 'Ports (JSON [1,2,3])', type: 'json' }, { name: 'device_id', label: 'Device', type: 'fk', fk: { resource: 'devices', displayField: 'name' } }, { name: 'virtual_machine_id', label: 'VM', type: 'fk', fk: { resource: 'virtual-machines', displayField: 'name' } }]) },
  'fhrp-groups': { label: 'FHRP Group', titleField: 'name', fields: [{ name: 'name', label: 'Name', type: 'text' }, { name: 'group_id', label: 'Group ID', type: 'number', required: true }, { name: 'protocol', label: 'Protocol', type: 'select', options: ['vrrp2', 'vrrp3', 'hsrp', 'glbp', 'carp'] }, { name: 'auth_type', label: 'Auth Type', type: 'text' }, { name: 'auth_key', label: 'Auth Key', type: 'text' }, ...common] },
  'fhrp-group-assignments': { label: 'FHRP Assignment', titleField: 'group_id', fields: [{ name: 'group_id', label: 'Group', type: 'fk', required: true, fk: { resource: 'fhrp-groups', displayField: 'name' } }, { name: 'interface_type', label: 'Interface Type', type: 'select', options: ['interface', 'vminterface'] }, { name: 'interface_id', label: 'Interface ID', type: 'text', required: true }, { name: 'priority', label: 'Priority', type: 'number' }, ...common] },
  // Circuits
  'providers': { label: 'Provider', titleField: 'name', fields: withName([slug]) },
  'provider-accounts': { label: 'Provider Account', titleField: 'name', fields: withName([{ name: 'account', label: 'Account', type: 'text', required: true }, { name: 'provider_id', label: 'Provider', type: 'fk', required: true, fk: { resource: 'providers', displayField: 'name' } }]) },
  'provider-networks': { label: 'Provider Network', titleField: 'name', fields: withName([{ name: 'provider_id', label: 'Provider', type: 'fk', required: true, fk: { resource: 'providers', displayField: 'name' } }, { name: 'service_id', label: 'Service ID', type: 'text' }]) },
  'circuit-types': { label: 'Circuit Type', titleField: 'name', fields: withName([slug, { name: 'color', label: 'Color', type: 'color' }]) },
  'circuits': { label: 'Circuit', titleField: 'cid', fields: [{ name: 'cid', label: 'Circuit ID', type: 'text', required: true }, { name: 'provider_id', label: 'Provider', type: 'fk', required: true, fk: { resource: 'providers', displayField: 'name' } }, { name: 'provider_account_id', label: 'Provider Account', type: 'fk', fk: { resource: 'provider-accounts', displayField: 'name' } }, { name: 'type_id', label: 'Type', type: 'fk', required: true, fk: { resource: 'circuit-types', displayField: 'name' } }, { name: 'status', label: 'Status', type: 'select', options: ['planned', 'provisioning', 'active', 'offline', 'deprovisioning', 'decommissioned'] }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, { name: 'install_date', label: 'Install Date', type: 'text' }, { name: 'termination_date', label: 'Termination Date', type: 'text' }, { name: 'commit_rate', label: 'Commit Rate (kbps)', type: 'number' }, ...common] },
  'circuit-terminations': { label: 'Circuit Termination', titleField: 'circuit_id', fields: [{ name: 'circuit_id', label: 'Circuit', type: 'fk', required: true, fk: { resource: 'circuits', displayField: 'cid' } }, { name: 'term_side', label: 'Side', type: 'select', options: ['A', 'Z'] }, { name: 'site_id', label: 'Site', type: 'fk', fk: { resource: 'sites', displayField: 'name' } }, { name: 'provider_network_id', label: 'Provider Network', type: 'fk', fk: { resource: 'provider-networks', displayField: 'name' } }, { name: 'port_speed', label: 'Port Speed (kbps)', type: 'number' }, { name: 'upstream_speed', label: 'Upstream Speed (kbps)', type: 'number' }, { name: 'xconnect_id', label: 'Cross-connect ID', type: 'text' }, { name: 'pp_info', label: 'Patch Panel Info', type: 'text' }, ...common] },
  // Power
  'power-panels': { label: 'Power Panel', titleField: 'name', fields: withName([{ name: 'site_id', label: 'Site', type: 'fk', required: true, fk: { resource: 'sites', displayField: 'name' } }, { name: 'location_id', label: 'Location', type: 'fk', fk: { resource: 'locations', displayField: 'name' } }]) },
  'power-feeds': { label: 'Power Feed', titleField: 'name', fields: withName([{ name: 'power_panel_id', label: 'Power Panel', type: 'fk', required: true, fk: { resource: 'power-panels', displayField: 'name' } }, { name: 'rack_id', label: 'Rack', type: 'fk', fk: { resource: 'racks', displayField: 'name' } }, { name: 'status', label: 'Status', type: 'select', options: ['planned', 'active', 'failed', 'offline'] }, { name: 'type', label: 'Type', type: 'select', options: ['primary', 'redundant'] }, { name: 'supply', label: 'Supply', type: 'select', options: ['ac', 'dc'] }, { name: 'phase', label: 'Phase', type: 'select', options: ['single-phase', 'three-phase'] }, { name: 'voltage', label: 'Voltage', type: 'number' }, { name: 'amperage', label: 'Amperage', type: 'number' }, { name: 'max_utilization', label: 'Max Utilization %', type: 'number' }]) },
  // Virtualization
  'cluster-types': { label: 'Cluster Type', titleField: 'name', fields: withName([slug]) },
  'cluster-groups': { label: 'Cluster Group', titleField: 'name', fields: withName([slug]) },
  'clusters': { label: 'Cluster', titleField: 'name', fields: withName([{ name: 'type_id', label: 'Type', type: 'fk', required: true, fk: { resource: 'cluster-types', displayField: 'name' } }, { name: 'group_id', label: 'Group', type: 'fk', fk: { resource: 'cluster-groups', displayField: 'name' } }, { name: 'status', label: 'Status', type: 'select', options: ['planned', 'staging', 'active', 'decommissioning', 'offline'] }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, { name: 'site_id', label: 'Site', type: 'fk', fk: { resource: 'sites', displayField: 'name' } }]) },
  'virtual-machines': { label: 'Virtual Machine', titleField: 'name', fields: withName([{ name: 'status', label: 'Status', type: 'select', options: ['offline', 'active', 'planned', 'staged', 'failed', 'decommissioning'] }, { name: 'cluster_id', label: 'Cluster', type: 'fk', fk: { resource: 'clusters', displayField: 'name' } }, { name: 'device_id', label: 'Device', type: 'fk', fk: { resource: 'devices', displayField: 'name' } }, { name: 'role_id', label: 'Role', type: 'fk', fk: { resource: 'device-roles', displayField: 'name' } }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, { name: 'platform_id', label: 'Platform', type: 'fk', fk: { resource: 'platforms', displayField: 'name' } }, { name: 'vcpus', label: 'vCPUs', type: 'number' }, { name: 'memory', label: 'Memory (MB)', type: 'number' }, { name: 'disk', label: 'Disk (GB)', type: 'number' }, { name: 'serial', label: 'Serial', type: 'text' }, { name: 'site_id', label: 'Site', type: 'fk', fk: { resource: 'sites', displayField: 'name' } }]) },
  'vm-interfaces': { label: 'VM Interface', titleField: 'name', fields: [{ name: 'virtual_machine_id', label: 'VM', type: 'fk', required: true, fk: { resource: 'virtual-machines', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'enabled', label: 'Enabled', type: 'boolean' }, { name: 'mtu', label: 'MTU', type: 'number' }, { name: 'mac_address', label: 'MAC Address', type: 'text' }, { name: 'mode', label: 'Mode', type: 'select', options: ['', 'access', 'tagged', 'tagged-all'] }, { name: 'vrf_id', label: 'VRF', type: 'fk', fk: { resource: 'vrfs', displayField: 'name' } }, ...common] },
  'virtual-disks': { label: 'Virtual Disk', titleField: 'name', fields: [{ name: 'virtual_machine_id', label: 'VM', type: 'fk', required: true, fk: { resource: 'virtual-machines', displayField: 'name' } }, { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'size', label: 'Size (MB)', type: 'number', required: true }, ...common] },
  // Wireless
  'wireless-lan-groups': { label: 'Wireless LAN Group', titleField: 'name', fields: withName([slug, { name: 'parent_id', label: 'Parent', type: 'fk', fk: { resource: 'wireless-lan-groups', displayField: 'name' } }]) },
  'wireless-lans': { label: 'Wireless LAN', titleField: 'ssid', fields: [{ name: 'ssid', label: 'SSID', type: 'text', required: true }, { name: 'group_id', label: 'Group', type: 'fk', fk: { resource: 'wireless-lan-groups', displayField: 'name' } }, { name: 'status', label: 'Status', type: 'select', options: ['active', 'reserved', 'disabled', 'deprecated'] }, { name: 'vlan_id', label: 'VLAN', type: 'fk', fk: { resource: 'vlans', displayField: 'name' } }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, { name: 'auth_type', label: 'Auth Type', type: 'select', options: ['open', 'wep', 'wpa-personal', 'wpa-enterprise'] }, { name: 'auth_cipher', label: 'Auth Cipher', type: 'select', options: ['auto', 'tkip', 'aes'] }, { name: 'auth_psk', label: 'Auth PSK', type: 'text' }, ...common] },
  'wireless-links': { label: 'Wireless Link', titleField: 'ssid', fields: [{ name: 'interface_a_id', label: 'Interface A', type: 'fk', required: true, fk: { resource: 'interfaces', displayField: 'name' } }, { name: 'interface_b_id', label: 'Interface B', type: 'fk', required: true, fk: { resource: 'interfaces', displayField: 'name' } }, { name: 'ssid', label: 'SSID', type: 'text' }, { name: 'status', label: 'Status', type: 'select', options: ['connected', 'planned', 'decommissioning'] }, { name: 'auth_type', label: 'Auth Type', type: 'select', options: ['open', 'wep', 'wpa-personal', 'wpa-enterprise'] }, { name: 'distance', label: 'Distance', type: 'number' }, ...common] },
  // VPN
  'l2vpns': { label: 'L2VPN', titleField: 'name', fields: withName([slug, { name: 'identifier', label: 'Identifier', type: 'number' }, { name: 'type', label: 'Type', type: 'select', options: ['vxlan', 'vpws', 'vpls', 'mpls-evpn', 'pbb-evpn', 'epl', 'evpl', 'ep-lan', 'evp-lan', 'ep-tree', 'evp-tree'] }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }]) },
  'l2vpn-terminations': { label: 'L2VPN Termination', titleField: 'l2vpn_id', fields: [{ name: 'l2vpn_id', label: 'L2VPN', type: 'fk', required: true, fk: { resource: 'l2vpns', displayField: 'name' } }, { name: 'assigned_object_type', label: 'Object Type', type: 'select', options: ['vlan', 'interface', 'vminterface'] }, { name: 'assigned_object_id', label: 'Object ID', type: 'text', required: true }, ...common] },
  'tunnel-groups': { label: 'Tunnel Group', titleField: 'name', fields: withName([slug]) },
  'tunnels': { label: 'Tunnel', titleField: 'name', fields: withName([{ name: 'group_id', label: 'Group', type: 'fk', fk: { resource: 'tunnel-groups', displayField: 'name' } }, { name: 'status', label: 'Status', type: 'select', options: ['planned', 'active', 'disabled'] }, { name: 'encapsulation', label: 'Encapsulation', type: 'select', options: ['gre', 'ip-ip', 'ipsec-transport', 'ipsec-tunnel', 'wireguard', 'openvpn', 'l2tp', 'pptp'] }, { name: 'ipsec_profile_id', label: 'IPSec Profile', type: 'fk', fk: { resource: 'ipsec-profiles', displayField: 'name' } }, { name: 'tenant_id', label: 'Tenant', type: 'fk', fk: { resource: 'tenants', displayField: 'name' } }, { name: 'tunnel_id', label: 'Tunnel ID', type: 'number' }]) },
  'tunnel-terminations': { label: 'Tunnel Termination', titleField: 'tunnel_id', fields: [{ name: 'tunnel_id', label: 'Tunnel', type: 'fk', required: true, fk: { resource: 'tunnels', displayField: 'name' } }, { name: 'role', label: 'Role', type: 'select', options: ['peer', 'hub', 'spoke'] }, { name: 'termination_type', label: 'Termination Type', type: 'select', options: ['interface', 'vminterface'] }, { name: 'termination_id', label: 'Termination ID', type: 'text', required: true }, { name: 'outside_ip_id', label: 'Outside IP', type: 'fk', fk: { resource: 'ip-addresses', displayField: 'address' } }, ...common] },
  'ike-proposals': { label: 'IKE Proposal', titleField: 'name', fields: withName([{ name: 'authentication_method', label: 'Auth Method', type: 'select', options: ['preshared-keys', 'certificates', 'rsa-signatures', 'dsa-signatures'] }, { name: 'encryption_algorithm', label: 'Encryption', type: 'text' }, { name: 'authentication_algorithm', label: 'Auth Algo', type: 'text' }, { name: 'group', label: 'DH Group', type: 'number' }, { name: 'sa_lifetime', label: 'SA Lifetime', type: 'number' }]) },
  'ike-policies': { label: 'IKE Policy', titleField: 'name', fields: withName([{ name: 'version', label: 'Version', type: 'number' }, { name: 'mode', label: 'Mode', type: 'select', options: ['', 'main', 'aggressive'] }, { name: 'proposals', label: 'Proposals (JSON ["id1", "id2"])', type: 'json' }, { name: 'preshared_key', label: 'Preshared Key', type: 'text' }]) },
  'ipsec-proposals': { label: 'IPSec Proposal', titleField: 'name', fields: withName([{ name: 'encryption_algorithm', label: 'Encryption', type: 'text' }, { name: 'authentication_algorithm', label: 'Auth Algo', type: 'text' }, { name: 'sa_lifetime_seconds', label: 'SA Lifetime (s)', type: 'number' }, { name: 'sa_lifetime_data', label: 'SA Lifetime (data)', type: 'number' }]) },
  'ipsec-policies': { label: 'IPSec Policy', titleField: 'name', fields: withName([{ name: 'proposals', label: 'Proposals (JSON)', type: 'json' }, { name: 'pfs_group', label: 'PFS Group', type: 'number' }]) },
  'ipsec-profiles': { label: 'IPSec Profile', titleField: 'name', fields: withName([{ name: 'mode', label: 'Mode', type: 'select', options: ['esp', 'ah'] }, { name: 'ike_policy_id', label: 'IKE Policy', type: 'fk', required: true, fk: { resource: 'ike-policies', displayField: 'name' } }, { name: 'ipsec_policy_id', label: 'IPSec Policy', type: 'fk', required: true, fk: { resource: 'ipsec-policies', displayField: 'name' } }]) },
  // Customization
  'tags': { label: 'Tag', titleField: 'name', fields: withName([slug, { name: 'color', label: 'Color', type: 'color' }, { name: 'object_types', label: 'Object Types (JSON)', type: 'json' }]) },
  'custom-fields': { label: 'Custom Field', titleField: 'name', fields: withName([{ name: 'label', label: 'Label', type: 'text' }, { name: 'type', label: 'Type', type: 'select', options: ['text', 'longtext', 'integer', 'decimal', 'boolean', 'date', 'datetime', 'url', 'json', 'select', 'multiselect', 'object', 'multiobject'] }, { name: 'object_types', label: 'Object Types (JSON)', type: 'json', required: true }, { name: 'required', label: 'Required', type: 'boolean' }, { name: 'default', label: 'Default', type: 'text' }, { name: 'choices', label: 'Choices (JSON)', type: 'json' }, { name: 'weight', label: 'Weight', type: 'number' }]) },
  'custom-links': { label: 'Custom Link', titleField: 'name', fields: withName([{ name: 'object_types', label: 'Object Types (JSON)', type: 'json', required: true }, { name: 'link_text', label: 'Link Text', type: 'text', required: true }, { name: 'link_url', label: 'Link URL', type: 'text', required: true }, { name: 'weight', label: 'Weight', type: 'number' }, { name: 'group_name', label: 'Group Name', type: 'text' }, { name: 'new_window', label: 'New Window', type: 'boolean' }, { name: 'enabled', label: 'Enabled', type: 'boolean' }]) },
  'config-contexts': { label: 'Config Context', titleField: 'name', fields: withName([{ name: 'weight', label: 'Weight', type: 'number' }, { name: 'data', label: 'Data (JSON)', type: 'json', required: true }, { name: 'is_active', label: 'Active', type: 'boolean' }]) },
  'config-templates': { label: 'Config Template', titleField: 'name', fields: withName([{ name: 'template_code', label: 'Jinja2 Template', type: 'textarea', required: true }, { name: 'environment_params', label: 'Environment Params (JSON)', type: 'json' }]) },
  'webhooks': { label: 'Webhook', titleField: 'name', fields: withName([{ name: 'object_types', label: 'Object Types (JSON)', type: 'json', required: true }, { name: 'type_create', label: 'On Create', type: 'boolean' }, { name: 'type_update', label: 'On Update', type: 'boolean' }, { name: 'type_delete', label: 'On Delete', type: 'boolean' }, { name: 'payload_url', label: 'Payload URL', type: 'text', required: true }, { name: 'enabled', label: 'Enabled', type: 'boolean' }, { name: 'http_method', label: 'HTTP Method', type: 'select', options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] }, { name: 'http_content_type', label: 'Content Type', type: 'text' }, { name: 'secret', label: 'Secret', type: 'text' }, { name: 'ssl_verification', label: 'SSL Verify', type: 'boolean' }]) },
  'saved-filters': { label: 'Saved Filter', titleField: 'name', fields: withName([slug, { name: 'object_types', label: 'Object Types (JSON)', type: 'json', required: true }, { name: 'parameters', label: 'Parameters (JSON)', type: 'json', required: true }, { name: 'weight', label: 'Weight', type: 'number' }, { name: 'enabled', label: 'Enabled', type: 'boolean' }, { name: 'shared', label: 'Shared', type: 'boolean' }]) },
  'journal-entries': { label: 'Journal Entry', titleField: 'comments', fields: [{ name: 'assigned_object_type', label: 'Object Type', type: 'text', required: true }, { name: 'assigned_object_id', label: 'Object ID', type: 'text', required: true }, { name: 'kind', label: 'Kind', type: 'select', options: ['info', 'success', 'warning', 'danger'] }, { name: 'comments', label: 'Comments', type: 'textarea', required: true }, ...common] },
  'image-attachments': { label: 'Image Attachment', titleField: 'name', fields: [{ name: 'object_type', label: 'Object Type', type: 'text', required: true }, { name: 'object_id', label: 'Object ID', type: 'text', required: true }, { name: 'name', label: 'Name', type: 'text' }, { name: 'image', label: 'Image (URL or base64)', type: 'textarea', required: true }, ...common] },
};

// Default columns to show in list views
export function getDefaultColumns(resource) {
  const r = RESOURCES[resource];
  if (!r) return ['id'];
  const titleField = r.titleField || 'name';
  const cols = [titleField];
  const fieldNames = r.fields.map((f) => f.name);
  for (const k of ['status', 'slug', 'site_id', 'role_id', 'type', 'protocol', 'ports', 'tenant_id', 'address', 'prefix', 'vid', 'asn', 'cid', 'provider_id', 'manufacturer_id', 'model', 'device_id', 'description', 'last_updated']) {
    if (fieldNames.includes(k) && !cols.includes(k)) {
      cols.push(k);
      if (cols.length >= 6) break;
    }
  }
  return cols;
}
